name: Push to Test Repo

on:
  push:
    branches:
      - main

jobs:
  push-to-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend repo
        uses: actions/checkout@v2

      - name: Push changes to Test repo
        run: |
          # Clone Test repo
          git clone https://github.com/Fitness-Mate/Test.git ../Test
          # Copy Frontend repo contents to Test repo
          cp -r ./* ../Test/
          # CD to Test repo and commit & push changes
          cd ../Test
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update from Frontend repo by ${{ github.actor }}"
          git push https://x-access-token:${{ secrets.fitmate }}@github.com/Fitness-Mate/Test.git main
