name: Push to forked Repo

on:
  push:
    branches: [main]

jobs:
  push-to-personal-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Clone main Repo
        run: |
          git clone https://github.com/staccato20/FitnessMate-FE-Deploy main

      - name: Copy changes to main Repo
        run: |
          rsync -av --exclude='.git' --exclude='node_modules/' --exclude='main/' . main/
          ls -al main/  # 복사된 파일 목록 확인

      - name: Commit and Push changes to main repo main branch
        run: |
          cd main
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git status  # 변경된 파일 목록 확인
          git add -A  # 모든 변경 사항 추가
          git commit -m "Update from Frontend repo by ${{ github.actor }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.FITMATE_STACCATO20 }}@github.com/staccato20/FitnessMate-FE-Deploy.git main
