# ---------- staccato20 repository deploy ----------

name: Push to forked Repo

on:
  push:
    branches:
      - main

jobs:
  push-to-personal-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend repo
        uses: actions/checkout@v2

      - name: Clone main Repo
        run: |
          git clone https://github.com/staccato20/FitnessMate-FE-Deploy main

      - name: Copy changes to main Repo
        run: |
          rsync -av --exclude='.git' --exclude='main/' . main/

      - name: Push changes to main repo main branch
        run: |
          cd main
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update from Frontend repo by ${{ github.actor }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.AUTO_STACCATO20 }}@github.com/staccato20/FitnessMate-FE-Deploy.git main

# ---------- Whoknow77 repository deploy ----------

# name: Push to Test Repo

# on:
#   push:
#     branches:
#       - test

# jobs:
#   push-to-personal-repo:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Frontend repo
#         uses: actions/checkout@v2

#       - name: Clone test Repo
#         run: |
#           git clone https://github.com/Whoknow77/fitnessmate-frontend.git ../test

#       - name: Copy changes to test Repo
#         run: |
#           cp -r ./* ../test/

#       - name: Push changes to test repo main branch
#         run: |
#           cd ../test
#           git config user.name "${{ github.actor }}"
#           git config user.email "${{ github.actor }}@users.noreply.github.com"
#           git add .
#           git commit -m "Update from Frontend repo by ${{ github.actor }}"
#           git push https://x-access-token:${{ secrets.fitmate }}@github.com/Whoknow77/fitnessmate-frontend.git main
