name: push to Deploy Repo

on:
  pull_request:
    branches: main

jobs:
  push-to-deploy-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy files to Deploy Repo
        run: |
          rsync -av --delete --exclude='.git' --exclude='node_modules/' --exclude='deploy/' --progress . deploy/
          ls -al deploy/

      - name: Commit and Push changes to Deploy Repo deploy branch
        run: |
          cd deploy
          git init
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b deploy
          git add -A
          git commit -m "Update from Frontend repo by ${{ github.actor }}" || echo "No changes to commit"
          git push -u https://x-access-token:${{ secrets.FITMATE_STACCATO20 }}@github.com/staccato20/FitnessMate-FE-Deploy.git deploy
