# ---------- staccato20 repository deploy ----------

name: Push to forked Repo

on:
  push:
    branches:
      - main

jobs:
  push-to-personal-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Clone main Repo
        run: |
          git clone https://github.com/staccato20/FitnessMate-FE-Deploy main

      # 종속성 설치 단계
      - name: Install Dependencies
        run: |
          cd main
          npm install

      # Storybook 빌드 단계
      - name: Build Storybook
        run: |
          cd main
          npm run build-storybook
          mv ./storybook-static ./build/storybook

      # 스토리북 로그 출력 추가
      - name: Display Storybook build logs
        run: |
          ls -l main/storybook-static || (echo "No files found in /tmp/chromatic-build" && exit 1)

      # 토큰 환경변수 설정 여부 확인 단계 추가
      - name: Print environment variable for debugging
        run: |
          echo "CHROMATIC_PROJECT_TOKEN is set: ${CHROMATIC_PROJECT_TOKEN:+true}"
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookDirectory: storybook-static

      # Chromatic 실행 단계
      - name: Run Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          cd main
          npm run chromatic

      - name: Copy changes to main Repo
        run: |
          rsync -av --exclude='.git' --exclude='main/' . main/

      - name: Commit and Push changes to main repo main branch
        run: |
          cd main
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update from Frontend repo by ${{ github.actor }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.FITMATE_STACCATO20 }}@github.com/staccato20/FitnessMate-FE-Deploy.git main

# ---------- Whoknow77 repository deploy ----------

# name: Push to Test Repo

# on:
#   push:
#     branches:
#       - test

# jobs:
#   push-to-personal-repo:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Frontend repo
#         uses: actions/checkout@v2

#       - name: Clone test Repo
#         run: |
#           git clone https://github.com/Whoknow77/fitnessmate-frontend.git ../test

#       - name: Copy changes to test Repo
#         run: |
#           cp -r ./* ../test/

#       - name: Push changes to test repo main branch
#         run: |
#           cd ../test
#           git config user.name "${{ github.actor }}"
#           git config user.email "${{ github.actor }}@users.noreply.github.com"
#           git add .
#           git commit -m "Update from Frontend repo by ${{ github.actor }}"
#           git push https://x-access-token:${{ secrets.fitmate }}@github.com/Whoknow77/fitnessmate-frontend.git main
