# ---------- staccato20 repository deploy ----------

name: Push to forked Repo

on:
  pull_request:
    branches: [main] # main 브랜치에서 Pull Request 발생 시 실행

jobs:
  push-to-personal-repo:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the Frontend repo
      - name: Checkout Frontend repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      # 2. Clone the main repository
      - name: Clone main Repo
        run: |
          git clone https://github.com/staccato20/FitnessMate-FE-Deploy main

      # 3. Install dependencies in the cloned main repository
      - name: Install Dependencies
        run: |
          cd main
          npm install

      # 4. Optional: Copy changes to the main Repo (if necessary)
      - name: Copy changes to main Repo
        run: |
          rsync -av --exclude='.git' --exclude='main/' . main/

      # 5. Commit and push changes to the main repository's main branch
      - name: Commit and Push changes to main repo main branch
        run: |
          cd main
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update from Frontend repo by ${{ github.actor }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.FITMATE_STACCATO20 }}@github.com/staccato20/FitnessMate-FE-Deploy.git main
