name: "Main Repository Deploy"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code with full history to ensure latest state
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Clear cache and build artifacts
      - name: Clear cache and build artifacts
        run: |
          rm -rf node_modules .cache storybook-static main/node_modules

      # Install dependencies in the main repo
      - name: Install Dependencies
        run: |
          npm ci

      # Optional: Build Storybook if needed for local purposes
      - name: Build Storybook (Optional)
        run: npm run build-storybook

      # Optional: Deploy or copy changes to another repo if necessary
      - name: Copy changes to another repository
        run: |
          # Add commands to copy or deploy changes if needed
          echo "Copying files..."
